
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TESIS = 5;
  public static final int INT2STR = 32;
  public static final int CLOG = 36;
  public static final int PC = 3;
  public static final int REPEAT = 17;
  public static final int DECL = 16;
  public static final int NOT = 11;
  public static final int AND = 9;
  public static final int IGUAL = 31;
  public static final int TYPE = 35;
  public static final int OR = 10;
  public static final int DIV = 28;
  public static final int BEGIN = 6;
  public static final int UNTIL = 18;
  public static final int NUM = 26;
  public static final int IF = 12;
  public static final int Q2STR = 23;
  public static final int EOF = 0;
  public static final int ASIG = 8;
  public static final int PENT = 25;
  public static final int error = 1;
  public static final int MUL = 22;
  public static final int COMA = 2;
  public static final int MENOS = 21;
  public static final int MENOR = 30;
  public static final int IDENT = 37;
  public static final int CSTR = 38;
  public static final int MAYOR = 29;
  public static final int OPUESTO = 33;
  public static final int CINT = 34;
  public static final int ELSE = 14;
  public static final int DEN = 27;
  public static final int THEN = 13;
  public static final int PROG = 15;
  public static final int END = 7;
  public static final int PAREN = 4;
  public static final int PRINT = 19;
  public static final int MAS = 20;
  public static final int Q2STRD = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMA",
  "PC",
  "PAREN",
  "TESIS",
  "BEGIN",
  "END",
  "ASIG",
  "AND",
  "OR",
  "NOT",
  "IF",
  "THEN",
  "ELSE",
  "PROG",
  "DECL",
  "REPEAT",
  "UNTIL",
  "PRINT",
  "MAS",
  "MENOS",
  "MUL",
  "Q2STR",
  "Q2STRD",
  "PENT",
  "NUM",
  "DEN",
  "DIV",
  "MAYOR",
  "MENOR",
  "IGUAL",
  "INT2STR",
  "OPUESTO",
  "CINT",
  "TYPE",
  "CLOG",
  "IDENT",
  "CSTR"
  };
}

